[build-system]
requires = ["setuptools>=68.0", "pybind11>=2.11.0"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
build = "cp311-* cp312-*"
skip = "*-win* *-musllinux*"
test-command = "python -c \"import whitematter; print('OK')\""

[tool.cibuildwheel.linux]
before-build = "yum install -y libomp-devel || apt-get install -y libomp-dev"

[tool.cibuildwheel.macos]
before-build = "brew install libomp"
