"""initial schema

Revision ID: d26468f2bcb5
Revises: 
Create Date: 2026-03-11 03:04:36.121515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd26468f2bcb5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blob_metadata',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('reference_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('datasets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('data_type', sa.String(length=20), nullable=True),
    sa.Column('format', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('num_classes', sa.Integer(), nullable=True),
    sa.Column('total_samples', sa.Integer(), nullable=True),
    sa.Column('train_samples', sa.Integer(), nullable=True),
    sa.Column('test_samples', sa.Integer(), nullable=True),
    sa.Column('input_shape', sa.JSON(), nullable=True),
    sa.Column('class_names', sa.JSON(), nullable=True),
    sa.Column('samples_per_class', sa.JSON(), nullable=True),
    sa.Column('preprocessing_config', sa.JSON(), nullable=True),
    sa.Column('raw_blob_key', sa.String(length=255), nullable=True),
    sa.Column('processed_blob_prefix', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('models',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dataset_id', sa.String(length=32), nullable=True),
    sa.Column('dataset_name', sa.String(length=255), nullable=True),
    sa.Column('architecture_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('epochs_trained', sa.Integer(), nullable=True),
    sa.Column('best_accuracy', sa.Float(), nullable=True),
    sa.Column('final_loss', sa.Float(), nullable=True),
    sa.Column('architecture_config', sa.JSON(), nullable=True),
    sa.Column('training_config', sa.JSON(), nullable=True),
    sa.Column('weights_blob_key', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('model_id', sa.String(length=32), nullable=False),
    sa.Column('worker_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('current_epoch', sa.Integer(), nullable=True),
    sa.Column('total_epochs', sa.Integer(), nullable=True),
    sa.Column('current_loss', sa.Float(), nullable=True),
    sa.Column('current_accuracy', sa.Float(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('generated_code_blob_key', sa.String(length=255), nullable=True),
    sa.Column('build_log_blob_key', sa.String(length=255), nullable=True),
    sa.Column('training_log_blob_key', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=True),
    sa.Column('epoch', sa.Integer(), nullable=False),
    sa.Column('loss', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('learning_rate', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['training_jobs.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_history')
    op.drop_table('training_jobs')
    op.drop_table('models')
    op.drop_table('datasets')
    op.drop_table('blob_metadata')
    # ### end Alembic commands ###
